coverage:
  status:
    patch:
        informational: true
        branches:
          - main
        if_ci_failed: error #set the status to success only if the CI is successful
        only_pulls: false #Only post a status to pull requests