codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: false
      tests:
        paths:
          - "tests/"
        target: 100%
      source:
        paths:
          - "src/"
        target: 97%
        threshold: 0.002
    patch:
      default:
        target: 80%