name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check

  werror:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Warnings
      run: cargo clippy -- -D warnings

  documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Missing documentation
      run: cargo clippy -- -D missing_docs
      
  test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Tests
      run: cargo test --no-fail-fast
